title: 记事本
tagline: 如灰尘保佑的礼物
description: >-
  9b9387's personal notebook.
url: ""
baseurl: ""
author:
  name: 9b9387
  github: 9b9387

theme: jekyll-theme-chirpy

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 10
lang: zh-CN
timezone: Asia/Shanghai

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-feed
  - jekyll-include-cache

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - tools
  - docs

# Chirpy Specifics
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
