title: 记事本
tagline: 如灰尘保佑的礼物
description: >-
  9b9387's personal notebook.
url: "https://biubiu.cool"
baseurl: ""
author:
  name: 9b9387
  github: 9b9387
  twitter: 9b9387

# The avatar on sidebar, support local or CORS resources
avatar: /assets/portfolio.png

social:
  links:
    - https://github.com/9b9387
    - https://twitter.com/9b9387

remote_theme: jekyll-theme-chirpy

# Build settings
markdown: kramdown
kramdown:
  math_engine: null
  syntax_highlighter: rouge
highlighter: rouge
paginate: 10
lang: zh-CN
timezone: Asia/Shanghai
toc: true

compress_html:
  blanklines: true
  ignore:
    envs: all

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      toc: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-include-cache

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - tools
  - docs

# Chirpy Specifics
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
